# Generated by Django 2.1.3 on 2018-11-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsChoiceness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.CharField(max_length=16)),
                ('goods_name', models.CharField(blank=True, max_length=128, null=True)),
                ('goods_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('goods_detail_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('goods_1_category', models.CharField(blank=True, max_length=32, null=True)),
                ('tao_bao_ke_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('goods_price', models.CharField(blank=True, max_length=8, null=True)),
                ('monthl_sales_volume', models.CharField(blank=True, max_length=32, null=True)),
                ('income_rate', models.CharField(blank=True, max_length=8, null=True)),
                ('commission', models.CharField(blank=True, max_length=8, null=True)),
                ('seller_wang_wang', models.CharField(blank=True, max_length=64, null=True)),
                ('seller_id', models.CharField(blank=True, max_length=16, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=128, null=True)),
                ('platform_type', models.CharField(blank=True, max_length=8, null=True)),
                ('discount_coupon_id', models.CharField(blank=True, max_length=64, null=True)),
                ('discount_coupon_sum', models.CharField(blank=True, max_length=8, null=True)),
                ('discount_coupon_residue', models.CharField(blank=True, max_length=8, null=True)),
                ('denomination', models.CharField(blank=True, max_length=128, null=True)),
                ('discount_coupon_begin_date', models.CharField(blank=True, max_length=64, null=True)),
                ('discount_coupon_end_date', models.CharField(blank=True, max_length=64, null=True)),
                ('generalize_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('discount_coupon_generalize_url', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'goods_choiceness',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsGroupbuying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.CharField(blank=True, max_length=16, null=True)),
                ('goods_name', models.CharField(blank=True, max_length=64, null=True)),
                ('goods_price', models.CharField(blank=True, max_length=8, null=True)),
                ('group_purchase_price', models.CharField(max_length=8)),
                ('group_purchase_number', models.CharField(blank=True, max_length=8, null=True)),
                ('goods_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('goods_begin_date', models.CharField(blank=True, max_length=1024, null=True)),
                ('goods_end_date', models.CharField(blank=True, max_length=8, null=True)),
                ('inventory_number', models.CharField(blank=True, max_length=8, null=True)),
                ('sold_number', models.CharField(blank=True, max_length=8, null=True)),
                ('remain_number', models.CharField(blank=True, max_length=8, null=True)),
                ('generalize_long_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('generalize_short_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('commission_rate', models.CharField(blank=True, max_length=8, null=True)),
                ('commission_price', models.CharField(blank=True, max_length=8, null=True)),
                ('primary_categories_id', models.CharField(blank=True, max_length=64, null=True)),
                ('primary_categories_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'goods_groupbuying',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=32, null=True)),
                ('seller_nickname', models.CharField(blank=True, max_length=32, null=True)),
                ('platform_type', models.CharField(blank=True, max_length=8, null=True)),
                ('goods_id', models.CharField(max_length=16)),
                ('goods_name', models.CharField(blank=True, max_length=64, null=True)),
                ('goods_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('goods_pic_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('goods_price', models.CharField(blank=True, max_length=8, null=True)),
                ('income_rate', models.CharField(blank=True, max_length=8, null=True)),
                ('discounts_denomination', models.CharField(blank=True, max_length=8, null=True)),
                ('discounts_sell_price', models.CharField(blank=True, max_length=8, null=True)),
                ('discounts_number', models.CharField(blank=True, max_length=11, null=True)),
                ('discounts_remain_number', models.CharField(blank=True, max_length=8, null=True)),
                ('discounts_begin_date', models.CharField(blank=True, max_length=64, null=True)),
                ('discounts_end_date', models.CharField(blank=True, max_length=64, null=True)),
                ('discounts_generalize_url', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'goods_quality',
                'managed': False,
            },
        ),
    ]
